CREATE TABLE IF NOT EXISTS CATEGORIAS (
                                          ID BIGINT AUTO_INCREMENT PRIMARY KEY,
                                          NOMBRE VARCHAR(100) NOT NULL UNIQUE,
    DESCRIPCION VARCHAR(500)
    );

CREATE TABLE IF NOT EXISTS GASTOS (
                                      ID BIGINT AUTO_INCREMENT PRIMARY KEY,
                                      DESCRIPCION VARCHAR(200) NOT NULL,
    MONTO DOUBLE NOT NULL,
    FECHA DATE NOT NULL,
    CATEGORIA_ID BIGINT,
    FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIAS(ID)
    );